address: "Töölönkatu 3 A, 00100 Helsinki, 5krs."
email: "pohjalaistentanssikerho.ry (ät) gmail.com"
links:
  signin: "https://docs.google.com/forms/d/e/1FAIpQLSdHkK7mxSwmHvHHZfv2AHSHZh2VXAEFnyVE0BJxWV3S0gGvXQ/viewform"
  facebook: "https://www.facebook.com/groups/pot.tanssikerho/"
  whatsapp: "https://chat.whatsapp.com/GW5RsQ8aocE29pmXUCY229"
  instagram: https://www.instagram.com/pohjalaistentanssikerho/
bank:
  name: "Holvi"
  payee: "Pohjalaisten tanssikerho ry"
  iban: "FI51 7997 7998 0564 23"
  bic: "HOLVFIHH"
navigation:
  header:
    - item:
        label: etusivu
        url: 
    - item:
        label: kausikurssit
        url: kurssi/
        subdir:
          - sub: kurssi_yleista
          - sub: kurssi_kausi
            title: Kurssikuvaukset
          - sub: kurssi_tiiviskurssit
            title: tiiviskurssit
    - item:
        label: tapahtumat
        url: tapahtuma/
        subdir:
          - sub: tapahtuma
    - item:
        label: hallitus
        url: hallitus/
    - item:
        label: blogi
        url: blogi/
        subdir:
          - sub: blogi
