baseURL: "https://pohjalaiset.fi/tanssikerho/"
title: "Pohjalaisten Tanssikerho"

DefaultContentLanguage: "fi"
languageCode: "fi-fi"

buildFuture: true
summaryLength: 35

params:
  address: "Töölönkatu 3 A, 00940 Helsinki, 5krs."
  links:
    signin: "https://docs.google.com/forms/d/e/1FAIpQLSd8_DLHRutiprjsUyHGdTFXJPiFp2lvzaUX623_8-yK4SqaOg/viewform"
    facebook: "https://www.facebook.com/groups/pot.tanssikerho/"
    whatsapp: "https://chat.whatsapp.com/GW5RsQ8aocE29pmXUCY229"
  bank:
    name: "Holvi"
    iban: "FI51 7997 7998 0564 23"
    bic: "HOLVFIHH"
  navigation:
    header:
      - item:
          label: etusivu
          url: 
      - item:
          label: kurssit
          url: kurssi/
          subdir:
            - sub: kurssi_yleista
            - sub: kurssi_kausi
              title: kurssit
            - sub: kurssi_tiiviskurssit
              title: tiiviskurssit
      - item:
          label: tapahtumat
          url: tapahtuma/
          subdir:
            - sub: tapahtuma
      - item:
          label: hallitus
          url: hallitus/
      - item:
          label: blogi
          url: blogi/
          subdir:
            - sub: blogi

taxonomies:
  category: categories
  subdirectory: subdirectories
