
baseURL: "https://musing-ardinghelli-ad83b1.netlify.com/"
title: "Pohjalaisten Tanssikerho"

DefaultContentLanguage: "fi"
languageCode: "fi-fi"

params:
  signin: "https://docs.google.com/forms/d/e/1FAIpQLScvIIl5l7a7bnPIYUmLxaijReK-bgoOt8C44nhTOxInNASBGg/viewform?usp=sf_link"
  bank:
    name: "Holvi"
    iban: "FI51 7997 7998 0564 23"
    bic: "HOLVFIHH"
