
baseURL: "https://musing-ardinghelli-ad83b1.netlify.com/"
title: "Pohjalaisten Tanssikerho"

DefaultContentLanguage: "fi"
languageCode: "fi-fi"

params:
  courseRegistration: ""
  bank:
    name: "Holvi"
    iban: "FI51 7997 7998 0564 23"
    bic: "HOLVFIHH"
