version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      # - run: apk update && apk add lftp
      - run: switch lftp
      - run: HUGO_ENV=production hugo --gc --minify -v -d $HUGO_BUILD_DIR
      - run: echo "hello world"
      - run: tree ~/hugo/public
