version: 2.1
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    # working_directory: ~/hugo
    # environment:
    #   HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - checkout
      - run:
          name: install lftp
          command: |
            sudo apt-get update;
            sudo apt-get install lftp
      - run: HUGO_ENV=production hugo --gc --minify -v
      - run: echo ${PASSWORD}
      - deploy:
          name: upload public
          command: |
            export LFTP_PASSWORD=${PASSWORD}
            lftp -c "open -u kwander --env-password sftp://porthan.osakunta.fi; set ftp:ssl-allow yes; set ssl:verify-certificate no; mirror -R public /group/other/tanssikerho/public_html"
