backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "blogi"
    label: "Blogi"
    folder: "content/blogi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['blogi']"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "kurssi"
    label: "Kurssit"
    folder: "content/blogi"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['kurssi']"}
      - { label: "Categories weight", name: "categories_weight", widget: "hidden", default: ""}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "ry"
    label: "Pohjalaisten tanssikerho ry"
    folder: "content/ry"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['ry']"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Sivut"
    files:
      - name: "etusivu"
        label: "Etusivu"
        file: "content/etusivu.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "hallitus"
        label: "Hallitus"
        file: "content/hallitus.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "tapahtumat"
        label: "Tapahtumat"
        file: "content/tapahtumat.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "sahkopostilista"
        label: "Sähköpostilista"
        file: "content/sahkopostilista.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
