backend:
  name: git-gateway
  branch: master
media_folder: "static/img"
public_folder: "/img"
site_url: https://musing-ardinghelli-ad83b1.netlify.com
display_url: https://musing-ardinghelli-ad83b1.netlify.com
editor:
  preview: false

collections:

  - name: "blog"
    label: "Blogi"
    description: "Voit lisätä blogikirjoituksia tai muokata niitä. Muista lisätä myös lyhyt kuvaus blogeille."
    folder: "content/blogi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['blogi']"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "couser"
    label: "Kurssit"
    description: "Kaikki kurssisivut, jotka näkyvät dropdown menussa."
    folder: "content/kurssi"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['kurssi']"}
      - { label: "Categories weight", name: "categories_weight", widget: "hidden", default: ""}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "footer"
    label: "Footer"
    description: "Kaikki linkit nettisivun alapalkissa, joita painamalla pääsee uudelle sivulle poistumatta pääsivuilta."
    folder: "content/ry"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['ry']"}
      - { label: "Categories weight", name: "categories_weight", widget: "number"}
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Sivut"
    description: "Yksittäiset sivut, jotka aukeavat yläpalkista, poislukien listaavat sivut."
    files:

      - name: "frontpage"
        label: "Etusivu"
        file: "content/etusivu.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }

      - name: "board"
        label: "Hallitus"
        file: "content/hallitus.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }

      - name: "events"
        label: "Tapahtumat"
        file: "content/tapahtumat.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }

      - name: "mailinglist"
        label: "Sähköpostilista"
        file: "content/sahkopostilista.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }

# data

      - name: "coursesMeta"
        label: "Kurssi-info"
        file: "data/coursesMeta.json"
        widget: "list"
        fields:
          - name: "alkeet"
            label: "Alkeet vaihtuvilla pareilla"
            widget: "list"
            allow_add: false
            fields:
              # - { label: "Kurssi ID ÄLÄ MUUTA", name: "name", widget: "string" }
              - { label: "Opettaja", name: "teacher", widget: "string" }
              - { label: "Aloitus aika", name: "start", widget: "string" }
              - { label: "Lopetus aika", name: "end", widget: "string" }
          - name: "alkeetOma"
            label: "Alkeet oman parin kanssa"
            widget: "list"
            allow_add: false
            fields:
              # - { label: "Kurssi ID ÄLÄ MUUTA", name: "name", widget: "string" }
              - { label: "Opettaja", name: "teacher", widget: "string" }
              - { label: "Aloitus aika", name: "start", widget: "string" }
              - { label: "Lopetus aika", name: "end", widget: "string" }
          - name: "alkeisjatko"
            label: "Alkeisjatko"
            widget: "list"
            allow_add: false
            fields:
              # - { label: "Kurssi ID ÄLÄ MUUTA", name: "name", widget: "string" }
              - { label: "Opettaja", name: "teacher", widget: "string" }
              - { label: "Aloitus aika", name: "start", widget: "string" }
              - { label: "Lopetus aika", name: "end", widget: "string" }
          - name: "jatko"
            label: "Jatko"
            widget: "list"
            allow_add: false
            fields:
              # - { label: "Kurssi ID ÄLÄ MUUTA", name: "name", widget: "string" }
              - { label: "Opettaja", name: "teacher", widget: "string" }
              - { label: "Aloitus aika", name: "start", widget: "string" }
              - { label: "Lopetus aika", name: "end", widget: "string" }

# Unusable below 

      - name: "data"
        label: "Tietokannat"
        description: "Testissä vielä! Älä käytä!"
        files:
          - name: "board"
            label: "Hallituksen jäsenet"
            file: "data/board.json"
            widget: "object"
            fields:
              - { label: "Etunimi", name: "firstname", widget: "string" }
              - { label: "Sukunimi", name: "lastname", widget: "string" }
              - { label: "Kuva", name: "picture", widget: "string" }
              - { label: "Rooli", name: "role", widget: "string" }
              - { label: "Sähköposti", name: "email", widget: "string" }

      - name: "test"
        label: "Testi"
        file: "data/foo.json"
        widget: "list"
        fields:
          - { label: "Foo1", name: "foo1", widget: "string" }
          - { label: "Foo2", name: "foo2", widget: "string" }
          - { label: "Foo3", name: "foo3", widget: "string" }
          - label: "Foo4"
            name: "foo4"
            widget: "list"
            fields:
              - {label: "Foo5", name: "foo5", widget: "string" }

      - name: "dummy"
        label: "Test dummy board"
        file: "data/dummy.json"
        fields:
          - label: "Item"
            name: ""
            widget: "list"
            fields:
              - { label: "Etunimi", name: "firstname", widget: "string" }
              - { label: "Sukunimi", name: "lastname", widget: "string" }
              - { label: "Kuva", name: "picture", widget: "string" }
              - { label: "Rooli", name: "role", widget: "string" }
              - { label: "Sähköposti", name: "email", widget: "string" }

      - name: "listTest"
        label: "Example of list"
        file: "data/listTest.json"
        widget: "list"
        fields:
          - {label: "Quote", name: "quote", widget: "string", default: "Everything is awesome!"}
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
              - {label: "Name", name: "name", widget: "string", default: "Emmet"}
              - {label: "Avatar", name: "avatar", widget: "image", default: "/img/emmet.jpg"}

      - name: "objectTest"
        label: "Example of object"
        widget: "object"
        file: "data/objectTest.json"
        fields:
          - {label: "Public", name: "public", widget: "boolean", default: true}
          - {label: "Name", name: "name", widget: "string"}
          - label: "Birthdate"
            name: "birthdate"
            widget: "date"
            default: ""
            format: "MM/DD/YYYY"
          - label: "Address"
            name: "address"
            widget: "object"
            fields: 
              - {label: "Street Address", name: "street", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
              - {label: "Postal Code", name: "post-code", widget: "string"}


      # - name: "events"
      #   label: "Tapahtumat"
      #   file: "data/events.json"
      #   fields: 
      #     - { label: "Code", name: "code", widget: "code", default_language: "json" }
      # - name: "courses"
      #   label: "Kurssiaikataulu ja lajit"
      #   file: "data/courses.json"
      #   fields:
      #     - { label: "Code", name: "code", widget: "code", default_language: "json" }
