backend:
  name: git-gateway
  branch: master
media_folder: "static/media"
public_folder: "/media"
site_url: pohjalaiset.fi/tanssikerho
editor:
  preview: false

collections:

  - name: "blog"
    label: "Blogi"
    description: "Voit lisätä blogikirjoituksia tai muokata niitä. Muista lisätä myös lyhyt kuvaus blogeille."
    folder: "content/blogi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['blogi']"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "couser"
    label: "Kurssit"
    description: "Kaikki kurssisivut, jotka näkyvät dropdown menussa."
    folder: "content/kurssi"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['kurssi']"}
      - { label: "Categories weight", name: "categories_weight", widget: "hidden", default: ""}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "footer"
    label: "Footer"
    description: "Kaikki linkit nettisivujen alapalkissa, mitä painamalla pääsee uudelle sivulle poistumatta pohjalaisten nettisivuilta."
    folder: "content/ry"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['ry']"}
      - { label: "Categories weight", name: "categories_weight", widget: "number"}
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Sivut"
    description: "Yksittäiset sivut, jotka aukeavat yläpalkista, poislukien listaavat sivut."
    files:

      - name: "frontpage"
        label: "Etusivu"
        file: "content/etusivu.md"
        description: "Nettisivujen etusivu."
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }

      - name: "board"
        label: "Hallitus"
        file: "content/hallitus.md"
        description: "Hallitussivut. Hallituksen jäseniä lisätään tietokannan kautta."
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }

      - name: "events"
        label: "Tapahtumat"
        file: "content/tapahtumat.md"
        description: "Tapahtumasivut. Itse tapahtumia lisätään tietokannasta."
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }

      - name: "mailinglist"
        label: "Sähköpostilista"
        file: "content/sahkopostilista.md"
        description: "Ohjeet sähköpostilistalle liittymiseen."
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }

# data

  - name: "data"
    label: "Tietokannat"
    description: "Tietokannat sisältävät sivun listattavia asioita, kuten tapahtumat ja kurssit."
    files:

      - name: "events"
        label: "Tapahtumat"
        file: "data/events.json"
        description: "Lisää tai poista tapahtumia. HUOM! Kun lisäät tapahtuman, uusi kenttä ilmestyy sivun pohjalle!"
        widget: "list"
        fields: 
          - name: "events"
            label: "Tapahtuma"
            widget: "list"
            fields: 
              - { label: "Otsikko", name: "title", widget: "string" }
              - { label: "Päivämäärä", name: "date", widget: "date", format: "YYYY-MM-DD" }
              - { label: "Kuvaus", name: "description", widget: "markdown" }

      - name: "coursesMeta"
        label: "Kurssi-info"
        file: "data/coursesMeta.json"
        description: "Kursseihin liittyvää tietoa, kuten kurssien opettajat, kurssien aloitusajat sekä lopetusajat."
        widget: "list"
        fields:
          - name: "alkeet"
            label: "Alkeet vaihtuvilla pareilla"
            widget: "list"
            allow_add: false
            collapsed: false
            fields:
              # - { label: "Kurssi ID ÄLÄ MUUTA", name: "name", widget: "string" }
              - { label: "Opettaja", name: "teacher", widget: "string" }
              - { label: "Aloitus aika", name: "start", widget: "string" }
              - { label: "Lopetus aika", name: "end", widget: "string" }
          - name: "alkeetOma"
            label: "Alkeet oman parin kanssa"
            widget: "list"
            allow_add: false
            collapsed: false
            fields:
              # - { label: "Kurssi ID ÄLÄ MUUTA", name: "name", widget: "string" }
              - { label: "Opettaja", name: "teacher", widget: "string" }
              - { label: "Aloitus aika", name: "start", widget: "string" }
              - { label: "Lopetus aika", name: "end", widget: "string" }
          - name: "alkeisjatko"
            label: "Alkeisjatko"
            widget: "list"
            allow_add: false
            collapsed: false
            fields:
              # - { label: "Kurssi ID ÄLÄ MUUTA", name: "name", widget: "string" }
              - { label: "Opettaja", name: "teacher", widget: "string" }
              - { label: "Aloitus aika", name: "start", widget: "string" }
              - { label: "Lopetus aika", name: "end", widget: "string" }
          - name: "jatko"
            label: "Jatko"
            widget: "list"
            allow_add: false
            collapsed: false
            fields:
              # - { label: "Kurssi ID ÄLÄ MUUTA", name: "name", widget: "string" }
              - { label: "Opettaja", name: "teacher", widget: "string" }
              - { label: "Aloitus aika", name: "start", widget: "string" }
              - { label: "Lopetus aika", name: "end", widget: "string" }

      - name: "courses"
        label: "Kurssilajit ja aikataulut"
        file: "data/courses.json"
        description: "Lisää tai poista kurssilajeja kurssiaikatalusta."
        widget: "list"
        fields: 
          - name: "courses"
            label: "Kurssilajit ja aikataulut."
            description: "Jätä viestikenttä tyhjäksi! Jos viestikenttään kirjoittaa mitä tahansa, olettaa kone, että silloin ei pidetä tunteja ja näyttää kirjoitetun viestin."
            widget: "list"
            fields: 
              - { label: "Päivämäärä", name: "date", widget: "date", format: "YYYY-MM-DD" }
              - { label: "Viesti", name: "message", widget: "string", default: "" }
              - { label: "Alkeet vaihtuvilla pareilla", name: "alkeet", widget: "string" }
              - { label: "Alkeet oman parin kanssa", name: "alkeetOma", widget: "string" }
              - { label: "Alkeisjatko", name: "alkeisjatko", widget: "string" }
              - { label: "Jatko", name: "jatko", widget: "string" }

      - name: "board"
        label: "Halllituksen jäsenet"
        file: "data/board.json"
        description: "Hallitse kerhon hallituksen jäsenten tietoja, mm. sähköpostiosoitteita."
        widget: "list"
        fields:
          - name: "members"
            label: "Jäsen"
            widget: "list"
            fields:
              - { label: "Etunimi", name: "firstname", widget: "string" }
              - { label: "Sukunimi", name: "lastname", widget: "string" }
              - { label: "Kuva", name: "picture", widget: "string" }
              - { label: "Rooli", name: "role", widget: "string" }
              - { label: "Sähköposti", name: "email", widget: "string" }
