backend:
  name: git-gateway
  branch: master
media_folder: "static/media"
public_folder: "/media"
site_url: https://musing-ardinghelli-ad83b1.netlify.com
display_url: https://musing-ardinghelli-ad83b1.netlify.com

collections:
  - name: "blog"
    label: "Blogi"
    folder: "content/blogi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['blogi']"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "couser"
    label: "Kurssit"
    folder: "content/blogi"
    create: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['kurssi']"}
      - { label: "Categories weight", name: "categories_weight", widget: "hidden", default: ""}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "ry"
    label: "Pohjalaisten tanssikerho ry"
    folder: "content/ry"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['ry']"}
      - { label: "Categories weight", name: "categories_weight", widget: "number"}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Sivut"
    files:
      - name: "frontpage"
        label: "Etusivu"
        file: "content/etusivu.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "board"
        label: "Hallitus"
        file: "content/hallitus.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "events"
        label: "Tapahtumat"
        file: "content/tapahtumat.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
      - name: "mailinglist"
        label: "Sähköpostilista"
        file: "content/sahkopostilista.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "data"
    label: "Tietokannat"
    files:
      - name: "members"
        label: "Hallituksen jäsenet"
        file: "data/board.json"
        fields:
          # - { label: "Etunimi", name: "firstname", widget: "string" }
          # - { label: "Sukunimi", name: "lastname", widget: "string" }
          # - { label: "Kuvaus", name: "description", widget: "string" }
          # - { label: "Kuva", name: "picture", widget: "string" }
          # - { label: "Rooli", name: "role", widget: "string" }
          # - { label: "Sähköposti", name: "email", widget: "string" }
          - { label: "Code", name: "code", widget: "code", default_language: "json" }
      - name: "events"
        label: "Tapahtumat"
        file: "data/events.json"
        fields: 
          - { label: "Code", name: "code", widget: "code", default_language: "json" }
      - name: "courses"
        label: "Kurssiaikataulu ja lajit"
        file: "data/courses.json"
        fields:
          - { label: "Code", name: "code", widget: "code", default_language: "json" }
