backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "blogi"
    label: "Blogi"
    folder: "content/blogi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Pusblish Date", name: "date", widget: "datetime", default: "" }
      - { label: "Categories", name: "categories", widget: "list", default: "['blogi']"}
      - { label: "Description", name: "description", widget: "string" }
