backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/media"
public_folder: "/media"

collections:
  - name: "blogi"
    label: "Blogi"
    folder: "content/blogi"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Categories", name: "categories", widget: "hidden", default: "['blogi']"}
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - name: "etusivu"
        label: "Etusivu"
        file: "content/etusivu.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
    files:
      - name: "hallitus"
        label: "Etusivu"
        file: "content/hallitus.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
    files:
      - name: "tapahtumat"
        label: "Tapahtumat"
        file: "content/tapahtumat.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
    files:
      - name: "sahkopostilista"
        label: "Sähköpostilista"
        file: "content/sahkopostilista.md"
        fields: 
          - { label: "Body", name: "body", widget: "markdown" }
